"""empty message

Revision ID: 4262e03d1b54
Revises: 
Create Date: 2021-01-13 23:08:25.592803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4262e03d1b54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Children', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_column('Children', 'dOB')
    op.add_column('Grandchildren', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_column('Grandchildren', 'dOB')
    op.add_column('Greatgrandchildren', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_column('Greatgrandchildren', 'dOB')
    op.add_column('Tanko', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_column('Tanko', 'dOB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tanko', sa.Column('dOB', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Tanko', 'birthday')
    op.add_column('Greatgrandchildren', sa.Column('dOB', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Greatgrandchildren', 'birthday')
    op.add_column('Grandchildren', sa.Column('dOB', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Grandchildren', 'birthday')
    op.add_column('Children', sa.Column('dOB', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Children', 'birthday')
    # ### end Alembic commands ###
